name: HTML/CSS Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Обновляем до Node.js 20

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Debug: Print .stylelintrc.json content
        run: cat .stylelintrc.json

      - name: Run HTMLHint
        run: npx htmlhint .

      - name: Run Stylelint
        run: npx stylelint "**/*.css" --cache --fix